#!/bin/bash

# TODO check number of arguments
# TODO used named arguments

# check if the target program is running and has a window
matched=$(wmctrl -l -x | awk -v wm_class="$1" '{if ($3 == wm_class) print $1}')
if [ "$matched" ]; then
	target_window_id=$matched
	focussed_window_id=$(xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)" | awk '{print $5}')

	# check if the target window is the focussed window
	# Note: $((16#$x)) converts the given hexadecimal number to decimal
	if [ $((16#${target_window_id:2})) -eq $((16#${focussed_window_id:2})) ]
	then
		# minimize the window
		xwit -id $target_window_id -iconify
	else
		# bring the window to focus
		wmctrl -a $target_window_id -x -i
	fi
else
	# launch the application
	$2
fi
